# Generated by Django 5.1.3 on 2024-12-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorlog_delete_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('motion', 'Motion'), ('smoke', 'Smoke'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('gas', 'Gas')], max_length=20)),
                ('threshold_value', models.FloatField()),
            ],
            options={
                'db_table': 'thresholds',
            },
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('motion', 'Motion'), ('smoke', 'Smoke'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('gas', 'Gas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
        migrations.AlterModelTable(
            name='sensorlog',
            table='sensors_sensorlog',
        ),
    ]
