# Generated by Django 5.1.3 on 2024-12-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensorsthreshold_alter_sensor_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorsThreshold',
            new_name='Threshold',
        ),
    ]
