# Generated by Django 5.1.3 on 2024-12-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incidentreport_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='IPN',
            new_name='FDI',
        ),
    ]
